CREATE TABLE club_user
(
    ID bigint not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE authority
(
    name varchar(50) not null primary key
);

CREATE TABLE user_authority
(
    user_id        bigint      not null references club_user,
    authority_name varchar(50) not null references authority
);

INSERT INTO authority
VALUES ('ROLE_STUDENT', 'ROLE_TEACHER');

CREATE TABLE club
(
    id                 bigint      not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               varchar(50) not null,
    location_latitude  float       not null,
    location_longitude float       not null
);

CREATE TABLE club_section
(
    club_id    bigint not null references club,
    section_id bigint not null references section
);

CREATE TABLE section
(
    id   bigint      not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null
);

CREATE TABLE user_section
(
    user_id    bigint not null references club_user,
    section_id bigint not null references section
);


