CREATE TABLE club_user
(
    ID bigint not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE club_role
(
    name varchar(50) not null primary key
);

CREATE TABLE user_role
(
    user_id   bigint      not null references club_user,
    role_name varchar(50) not null references club_role
);

INSERT INTO user_role
VALUES ('ROLE_STUDENT', 'ROLE_TEACHER');


CREATE TABLE club
(
    ID   bigint      not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME varchar(50) not null
);
